### PR TITLE
Add the Unliked/disliked

### PR DESCRIPTION
**Pull request by arthurtalkgoal**
Undo the liked and disliked, and update the algorithm checking

### CODE REVIEW

**Comment by arthurtalkgoal** [comment]
I got error in TravisCI, but these seems not related to my codes by the dependencies?
```
npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
```

should we update the related npm?

**Comment by arthurtalkgoal** [comment]
Anyone can gimme some guidelines, I can fix the issue.

**Comment by rkaneriya** [comment]
Any update on the progress of un-like/un-disliked functionality?

**Comment by guymorita** [comment]
@arthurtalkgoal @rkaneriya thanks for the contributions. finally got it added in. https://github.com/guymorita/recommendationRaccoon/commit/4177b622c9c9c3bb57b4908e99b8004baea7612a

**Pull request closed without merging**
